// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func StoryView(initialStory string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"story-history\"><div class=\"story-page\"><p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(initialStory)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/story_view.templ`, Line: 6, Col: 20}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p></div></div><form id=\"response-form\" hx-post=\"/generate\" hx-target=\"#story-history\" hx-swap=\"innerHTML\" hx-indicator=\"#spinner\"><input type=\"text\" id=\"prompt\" name=\"prompt\" autofocus=\"autofocus\" placeholder=\"What do you do?\"> <button type=\"submit\">Send</button> <span id=\"word-count\">0/15 words</span></form><div id=\"inventory\"><h3>Inventory</h3><ul><!-- Items will be listed here --></ul></div><script>\n\t\tconst promptInput = document.getElementById('prompt');\n\t\tconst wordCountSpan = document.getElementById('word-count');\n\t\tconst responseForm = document.getElementById('response-form');\n\n\t\tpromptInput.addEventListener('input', () => {\n\t\t\tconst words = promptInput.value.trim().split(/\\s+/).filter(Boolean);\n\t\t\tlet wordCount = words.length;\n\t\t\tif (promptInput.value.trim() === \"\") {\n\t\t\t\twordCount = 0;\n\t\t\t}\n\t\t\twordCountSpan.textContent = `${wordCount}/15 words`;\n\t\t\tif (wordCount > 15) {\n\t\t\t\twordCountSpan.style.color = 'red';\n\t\t\t} else {\n\t\t\t\twordCountSpan.style.color = '#666';\n\t\t\t}\n\t\t});\n\n\t\tresponseForm.addEventListener('submit', (e) => {\n\t\t\tconst words = promptInput.value.trim().split(/\\s+/).filter(Boolean);\n\t\t\tif (words.length > 15) {\n\t\t\t\te.preventDefault();\n\t\t\t\talert('Your response cannot be more than 15 words.');\n\t\t\t}\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
